name: Deploy Azure Function App

on:
  push:
    branches:
      - main
    paths:
      # Something inside a directory
      - "**/*"
      # But not stuff that is not source code
      - "!.vscode/*"
      - "!.github/**/*"
      - "!*"

env:
  AZURE_FUNCTIONAPP_NAME: devgioele-poc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '16.x'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build function app
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          yarn
          yarn build
          yarn test
          popd
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}